version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - generator
      - frontend
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; bginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes: 
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  generator:
    image: gpt-2-dnd:latest
    expose: 
      - 8080
  frontend: 
    image: gpt-2-dnd-frontend:latest
    expose: 
      - 80
    links: 
      - generator
