version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - generator
      - frontend
  generator:
    image: gpt-2-dnd:latest
    expose: 
      - 8080
  frontend: 
    image: gpt-2-dnd-frontend:latest
    expose: 
      - 80
    links: 
      - generator
